// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htbrczdxerbbglfytfed.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0YnJjemR4ZXJiYmdsZnl0ZmVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5Njg4MjcsImV4cCI6MjA2MDU0NDgyN30.sHoNHz1-CNK14NWmkvjDJ62dN8mWtGOBz9Vups2tBbc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);